### ISSUE TITLE
Frame.replaceFieldType causes a cast exception from BigDecimal to Double

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#200]
Prior to **1.1.0-SNAPSHOT** I was re-mapping the Frame's **BigDecimal** type to **Double** type, e.g. _curFrame.replaceFieldType(field.dataType, StringType)_

I believe this feature hasn't been implemented with the Parquet rewrite.

Here's the exception:

Caused by: java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Double
	at scala.runtime.BoxesRunTime.unboxToDouble(BoxesRunTime.java:114)
	at io.eels.component.parquet.DoubleParquetValueWriter$.write(ParquetValueWriter.scala:134)
	at io.eels.component.parquet.RowWriter$$anonfun$writeRow$1.apply(RowWrite.scala:40)
	at io.eels.component.parquet.RowWriter$$anonfun$writeRow$1.apply(RowWrite.scala:37)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.eels.component.parquet.RowWriter.writeRow(RowWrite.scala:37)
	at io.eels.component.parquet.RowWriter.write(RowWrite.scala:32)
	at io.eels.component.parquet.RowWriteSupport.write(RowWrite.scala:24)
	at io.eels.component.parquet.RowWriteSupport.write(RowWrite.scala:10)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:123)
	at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:292)

**Comment by sksamuel** [comment]
Yes, we need to expand the JVM types supported for each data type. Ie, if we have a Decimal datatype then we should support java.lang.Double, java.lang.Float, BigDecimal, BigInteger, int, long etc.

**Comment by hannesmiller** [comment]
Nice! A good test is to run importer without changing a line of code - leave the replaceFieldType workaround for mapping Decimal to Double

**Comment by sksamuel** [comment]
You want 1.1.0-M1
