### ISSUE TITLE
HiveSource withPredicate method doesn't accept Decimal type

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#225]
- I have a column called *salary* defined as *decimal(38,5)* which fails on the following code:

```scala
    implicit val hadoopFileSystem = FileSystem.get(new Configuration())
    implicit val hiveMetaStoreClient = new HiveMetaStoreClient(new HiveConf())
    HiveSource("eel_test", "person")
      .withPredicate(Predicate.and(Predicate.equals("name", "Alice"), Predicate.gt("salary", 100)))
      .toFrame().collect().foreach(row => println(row))
```

1. I am passing an *int* but I think it should be able to coerce it to the target type of *decimal(38,5)*
2. Also we need a slot for Predicate.gt, Predicate.equals and other variants to support *decimal*

**Exception**

```
java.lang.IllegalArgumentException: FilterPredicate column: salary's declared type (java.lang.Integer) does not match the schema found in file metadata. Column salary is of type: FIXED_LEN_BYTE_ARRAY
Valid types for this column are: [class org.apache.parquet.io.api.Binary]
	at org.apache.parquet.filter2.predicate.ValidTypeMap.assertTypeValid(ValidTypeMap.java:125) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.validateColumn(SchemaCompatibilityValidator.java:181) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.validateColumnFilterPredicate(SchemaCompatibilityValidator.java:151) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:109) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:58) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.predicate.Operators$Gt.accept(Operators.java:236) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:122) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.visit(SchemaCompatibilityValidator.java:58) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.predicate.Operators$And.accept(Operators.java:309) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.predicate.SchemaCompatibilityValidator.validate(SchemaCompatibilityValidator.java:63) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.compat.RowGroupFilter.visit(RowGroupFilter.java:84) ~[parquet-hadoop-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.compat.RowGroupFilter.visit(RowGroupFilter.java:43) ~[parquet-hadoop-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.compat.FilterCompat$FilterPredicateCompat.accept(FilterCompat.java:126) ~[parquet-column-1.9.0.jar:1.9.0]
	at org.apache.parquet.filter2.compat.RowGroupFilter.filterRowGroups(RowGroupFilter.java:61) ~[parquet-hadoop-1.9.0.jar:1.9.0]
	at org.apache.parquet.hadoop.ParquetFileReader.filterRowGroups(ParquetFileReader.java:671) ~[parquet-hadoop-1.9.0.jar:1.9.0]
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:145) ~[parquet-hadoop-1.9.0.jar:1.9.0]
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:125) ~[parquet-hadoop-1.9.0.jar:1.9.0]
	at io.eels.component.parquet.util.ParquetIterator$$anonfun$apply$1.apply(ParquetIterator.scala:10) ~[eel-components_2.11-1.1.1.jar:1.1.1]
```

**Comment by sksamuel** [comment]
I don't think parquet can support predicates on big decimals, so you'd need to do a double predicate with a small range.

**Comment by hannesmiller** [comment]
I found the following related JIRAs on this issue, no resolutions but some suggested workarounds:

- https://issues.apache.org/jira/browse/PARQUET-281
- https://issues.apache.org/jira/browse/HIVE-10254

Perhaps we could create our own **UnboundRecordFilter** for Decimal types - I believe this will be pushed down on the read?

I wonder how Impala supports this...they certainly allow filtering on Decimals but whether they employ predicate pushdown is another thing?

**Comment by sksamuel** [comment]
Those tickets are still open, so I guess no decimal pushdowns are built in. However you can add user defined functions to do it, so we could add our own UDFs for types, where it is feasible. I don't know if the record groups contain enough information when they are storing decimals, as they might just see binary data and not keep the statistics we need.

**Comment by hannesmiller** [comment]
Fair enough! I was thinking that with the **UnboundRecordFilter** you could:

- Read the data in its native format (Decimal)
- Then coerce it to a double and do a range check - maybe with a tolerance threshold

**Comment by sksamuel** [comment]
How does a UnboundRecordFilter work?

**Comment by hannesmiller** [comment]
I will try and put an example together but I believe you bind it to a column somehow.

https://github.com/Parquet/parquet-mr/blob/master/parquet-column/src/main/java/parquet/filter/UnboundRecordFilter.java

**Comment by hannesmiller** [comment]
And it gets invoked in a column read

**Comment by sksamuel** [comment]
Yeah I looked at the interface but need to know what to do with the class. A full example is needed I think, and why a record filter is better than a udf.

**Comment by hannesmiller** [comment]
I wouldn't say one is better than the other - if you are using Parquet in the raw then a UDF is going to be new use to you.

Conversely if you are using Hive or Spark then a UDF is going to be very useful.

**Comment by sksamuel** [comment]
I've added support for custom user predicates. Now we can use that in order to implement ones for Decimal Type etc.

**Comment by sksamuel** [comment]
I've added support for decimal type predicates using user defined predicates. All very cool stuff :)
