### ISSUE TITLE
M1 release for AvroSink incorrectly converts a NIO Java path to a HDFS one

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#235]
- Code
```scala
   // Write to a AvroSink from a JDBCSource
    val query = "SELECT NAME, AGE, SALARY, CREATION_TIME FROM PERSON"
    val avroFilePath = Paths.get(s"${sys.props("user.home")}/person.avro")
    JdbcSource(() => dataSource.getConnection, query)
      .withFetchSize(10)
      .toFrame
      .replaceFieldType(DecimalType.Wildcard, DoubleType)
      .replaceFieldType(TimestampMillisType, StringType)
      .to(AvroSink(avroFilePath))
```
- Ok I think the offending code is as follows...the **apply** on *NIO* path calls **apply** on *File* which in turn creates **Path** Hadoop object - the problem is **file.toUri.toString** should be used to create the Hadoop **Path** object.

```scala
object AvroSink {
  def apply(file: File)(implicit conf: Configuration, fs: FileSystem): AvroSink = AvroSink(new Path(file.getAbsoluteFile.toString))
  def apply(path: java.nio.file.Path)(implicit conf: Configuration, fs: FileSystem): AvroSink = apply(path.toFile)
}
``` 
- StackTrace:
```
Exception in thread "main" java.lang.IllegalArgumentException: Pathname /C:/Users/millhan/person.avro from C:/Users/millhan/person.avro is not a valid DFS filename.
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:196)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:105)
	at org.apache.hadoop.hdfs.DistributedFileSystem$6.doCall(DistributedFileSystem.java:397)
	at org.apache.hadoop.hdfs.DistributedFileSystem$6.doCall(DistributedFileSystem.java:393)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:393)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:337)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:908)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:889)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:786)
	at io.eels.component.avro.AvroSink$$anon$1.<init>(AvroSink.scala:23)
	at io.eels.component.avro.AvroSink.writer(AvroSink.scala:21)
	at io.eels.actions.SinkAction$.execute(SinkAction.scala:10)
	at io.eels.Frame$class.to(Frame.scala:345)
	at io.eels.Frame$$anon$13.to(Frame.scala:151)
```

**Comment by sksamuel** [comment]
This looks like a Windows thing. Can you figure out why its broken Hannes
as its fine on linux.

**Comment by hannesmiller** [comment]
- I believe the offending code on windows is this:
```scala
  def apply(file: File)(implicit conf: Configuration, fs: FileSystem): AvroSink = AvroSink(new Path(file.getAbsoluteFile.toString))
```
- I think it should be:
```scala
  def apply(file: File)(implicit conf: Configuration, fs: FileSystem): AvroSink = AvroSink(new Path(file.toURI.toString))
```
-It works if I change my code to pass in a **Hadoop** path object using a **URI** string like so:
```scala
```
