### ISSUE TITLE
Problems serializing Lists and Maps in the AvroSource/Sink

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#241]
It appears that the serializers for **Avro** doesn't map **List** and **Map** to **java.util.List** and **java.util.Map** respectively.

- I have defined an EEL schema that looks like the following:
```scala
  StructType
    (Vector(Field(PERSON_DETAILS,StructType(
            Vector(Field(NAME,io.eels.schema.StringType$@9bd0fa6,true,false,None,false,null,Map()), 
                   Field(AGE,IntType(true),true,false,None,false,null,Map()), Field(SALARY,io.eels.schema.DoubleType$@46f699d5,true,false,None,false,null,Map()), 
                   Field(CREATION_TIME,LongType(true),true,false,None,false,null,Map()))),true,false,None,false,null,Map()), 
            Field(PHONE_NUMBERS,ArrayType(io.eels.schema.StringType$@9bd0fa6),true,false,None,false,null,Map())
    )
)
```
- Which equiates to:
```sql
Schema {
    PERSON_DETAILS: Struct {
        NAME: STRING,
        AGE: INT,
        CREATION_TIME:LONG
    }
    PHONE_NUMBERS: ARRAY[STRING]
}
```

-  The stack trace is as follows
```
Exception in thread "main" org.apache.avro.file.DataFileWriter$AppendWriteException: org.apache.avro.AvroRuntimeException: Unknown datum type [Ljava.lang.Object;: [Ljava.lang.Object;@55b5e331
	at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:308)
	at io.eels.component.avro.AvroWriter.write(AvroWriter.scala:24)
	at io.eels.component.avro.AvroSink$$anon$1.write(AvroSink.scala:25)
	at io.eels.Sink$$anonfun$write$1$$anonfun$apply$1.apply(Sink.scala:11)
	at io.eels.Sink$$anonfun$write$1$$anonfun$apply$1.apply(Sink.scala:11)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.eels.Sink$$anonfun$write$1.apply(Sink.scala:11)
	at io.eels.Sink$$anonfun$write$1.apply(Sink.scala:10)
	at com.sksamuel.exts.io.Using$class.using(Using.scala:9)
	at io.eels.component.avro.AvroSink.using(AvroSink.scala:11)
	at io.eels.Sink$class.write(Sink.scala:10)
	at io.eels.component.avro.AvroSink.write(AvroSink.scala:11)
	at io.eels.Sink4J.write(Sink4J.java:14)
	at io.eels.component.avro.AvroStructAndArraysTest.main(AvroStructAndArraysTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by sksamuel** [comment]
Can you confirm this again please as I thought it was working.

**Comment by sksamuel** [comment]
There was an array with lists which I've fixed now. Tests added for both lists and maps.

**Comment by sksamuel** [comment]
Backported to 1.2.x
