### ISSUE TITLE
HiveSinkWriter exception causes the writer thread to hang

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#243]
# Summary

The **HiveSinkWriter** raises the following exception:

```
10:45:17.646 [pool-9-thread-2] ERROR io.eels.component.hive.HiveSinkWriter - Could not perform write
org.apache.hadoop.hive.metastore.api.MetaException: Got exception: org.apache.hadoop.security.AccessControlException Permission denied: user=blah, access=WRITE, inode="/location/business_date=01-SEP-2016/type=mytype/version=1/batch_id=aa4a3ee6-bed2-4b1e-b81e-cb7bb38e7c2a":admin:supergroup:drwxrwxr-x
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:319)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:292)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:213)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:190)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1728)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1712)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1695)
	at org.apache.hadoop.hdfs.server.namenode.FSDirMkdirOp.mkdirs(FSDirMkdirOp.java:71)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirs(FSNamesystem.java:3896)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.mkdirs(NameNodeRpcServer.java:984)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.mkdirs(ClientNamenodeProtocolServerSideTranslatorPB.java:622)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
```
- This is due to me not having **write** permission on the underlying **HDFS** folder.

# Problem

The problem looks like the writer thread is blocked/locked on putting a row on the **LinkedBlockingQueue** called **buffer**, e.g.:
```
Stack trace: 
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:350)
io.eels.component.hive.HiveSinkWriter.write(HiveSinkWriter.scala:101)
io.eels.actions.SinkAction$$anonfun$execute$1.apply(SinkAction.scala:14)
io.eels.actions.SinkAction$$anonfun$execute$1.apply(SinkAction.scala:13)
scala.collection.Iterator$class.foreach(Iterator.scala:893)
io.eels.CloseableIterator$$anon$1.foreach(CloseableIterator.scala:9)
io.eels.CloseableIterator$class.foreach(CloseableIterator.scala:18)
io.eels.CloseableIterator$$anon$2.foreach(CloseableIterator.scala:26)
io.eels.actions.SinkAction$.execute(SinkAction.scala:13)
io.eels.Frame$class.to(Frame.scala:343)
io.eels.Frame$$anon$25.to(Frame.scala:287)
com.db.treasury.cassini.importer.GenericDatasetProcessor$$anonfun$1$$anon$1.call(GenericDatasetProcessor.scala:83)
com.db.treasury.cassini.importer.GenericDatasetProcessor$$anonfun$1$$anon$1.call(GenericDatasetProcessor.scala:62)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```
- I think for any exception you should bail out, e.g. in the catch block do something like the following:
```scala
  for (k <- 0 until ioThreads) {
    writerPool.submit {
      try {
        BlockingQueueConcurrentIterator(buffer, Row.Sentinel).foreach { row =>
          val writer = getOrCreateHiveWriter(row, k)._2
          // need to strip out any partition information from the written data and possibly pad
          writer.write(normalizer(row))
        }
      } catch {
        case NonFatal(e) =>
          logger.error("Could not perform write", e)
      }
    }
  }
```
- Perhaps you should change to have a **catch block** which shuts down all threads and re-throws the orignal exception, e.g.:
```scala
  for (k <- 0 until ioThreads) {
    writerPool.submit {
      try {
        BlockingQueueConcurrentIterator(buffer, Row.Sentinel).foreach { row =>
          val writer = getOrCreateHiveWriter(row, k)._2
          // need to strip out any partition information from the written data and possibly pad
          writer.write(normalizer(row))
        }
      } catch {
        case throwable:Throwable =>
           writerPool.shutdown()
           throw throwable
      }
    }
  }
```

**Comment by hannesmiller** [comment]
Nice way to quiesce but what I saw was a deadlock after examining all the  threads on jConsole,  i.e. other threads were blocked on the queue because the thread that raised the exception simply swallowed the exception and stayed in the loop I guess?

IMHO when an exception happens it's all bets are off and safer to bailout no? 

Otherwise you end up with partial writes - missing data?

- ShutdownNow should send a cancellation signal to all threads sitting on the queue and bailout.

If you don't agree I lim ok to run with this

**Comment by sksamuel** [comment]
In the change I pushed if one thread has an error, all the other threads will immediately stop out, and then the blocked thread (the caller) will be freed up. This is better than using shutdownNow, as that will just interrupt each thread, but each thread won't be blocked, but be processing the remainder of the rows. Ie, my change will result in an immediate cancellation, shutdownNow would result in a delayed cancellation, and what we had before was no cancellation.

**Comment by hannesmiller** [comment]
Ok

**Comment by sksamuel** [comment]
Fixed.
