### ISSUE TITLE
HiveSinkWriter gives: Rounding necessary exception and also swallows the exception

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#270]
# I think the following code in **HiveSinkWriter** should re-throw the exception as opposed to logging and swallowing it:

```scala
  for (k <- 0 until ioThreads) {
    writerPool.submit {
      try {
        BlockingQueueConcurrentIterator(buffer, Row.Sentinel).foreach { row =>
          val writer = getOrCreateHiveWriter(row, k)._2
          // need to strip out any partition information from the written data and possibly pad
          writer.write(normalizer(row))
        }
      } catch {
        case NonFatal(e) =>
          logger.error("Could not perform write", e)
      }
    }
  }
```

# Math Rounding Exception

```code
14:13:35.448 [pool-12-thread-1] ERROR io.eels.component.hive.HiveSinkWriter - Could not perform write
java.lang.ArithmeticException: Rounding necessary
	at java.math.BigDecimal.commonNeedIncrement(BigDecimal.java:4148) ~[?:1.8.0_71]
	at java.math.BigDecimal.needIncrement(BigDecimal.java:4204) ~[?:1.8.0_71]
	at java.math.BigDecimal.divideAndRound(BigDecimal.java:4112) ~[?:1.8.0_71]
	at java.math.BigDecimal.setScale(BigDecimal.java:2452) ~[?:1.8.0_71]
	at java.math.BigDecimal.setScale(BigDecimal.java:2512) ~[?:1.8.0_71]
	at scala.math.BigDecimal.setScale(BigDecimal.scala:662) ~[scala-library-2.11.8.jar:?]
	at io.eels.component.parquet.DecimalWriter.write(ParquetValueWriter.scala:97) ~[eel-components_2.11-1.1.1.jar:1.1.1]
	at io.eels.component.parquet.StructWriter$$anonfun$write$1.apply$mcVI$sp(ParquetValueWriter.scala:70) ~[eel-components_2.11-1.1.1.jar:1.1.1]
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) ~[scala-library-2.11.8.jar:?]
	at io.eels.component.parquet.StructWriter.write(ParquetValueWriter.scala:63) ~[eel-components_2.11-1.1.1.jar:1.1.1]
	at io.eels.component.parquet.RowWriter.write(RowWriteSupport.scala:39) ~[eel-components_2.11-1.1.1.jar:1.1.1]
	at io.eels.component.parquet.RowWriteSupport.write(RowWriteSupport.scala:30) ~[eel-components_2.11-1.1.1.jar:1.1.1]
	at io.eels.component.parquet.RowWriteSupport.write(RowWriteSupport.scala:13) ~[eel-components_2.11-1.1.1.jar:1.1.1]
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:123) ~[parquet-hadoop-1.9.0.jar:1.9.0]
	at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:292) ~[parquet-hadoop-1.9.0.jar:1.9.0]
	at io.eels.component.hive.dialect.ParquetHiveDialect$$anon$2.write(ParquetHiveDialect.scala:49) ~[eel-hive_2.11-1.1.1.jar:1.1.1]
	at io.eels.component.hive.HiveSinkWriter$$anonfun$2$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(HiveSinkWriter.scala:91) ~[eel-hive_2.11-1.1.1.jar:1.1.1]
	at io.eels.component.hive.HiveSinkWriter$$anonfun$2$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(HiveSinkWriter.scala:88) ~[eel-hive_2.11-1.1.1.jar:1.1.1]
	at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[scala-library-2.11.8.jar:?]
	at com.sksamuel.exts.collection.BlockingQueueConcurrentIterator.foreach(BlockingQueueConcurrentIterator.scala:10) ~[exts_2.11-1.42.0.jar:1.42.0]
	at io.eels.component.hive.HiveSinkWriter$$anonfun$2$$anonfun$apply$1.apply$mcV$sp(HiveSinkWriter.scala:88) [eel-hive_2.11-1.1.1.jar:1.1.1]
	at io.eels.component.hive.HiveSinkWriter$$anonfun$2$$anonfun$apply$1.apply(HiveSinkWriter.scala:87) [eel-hive_2.11-1.1.1.jar:1.1.1]
	at io.eels.component.hive.HiveSinkWriter$$anonfun$2$$anonfun$apply$1.apply(HiveSinkWriter.scala:87) [eel-hive_2.11-1.1.1.jar:1.1.1]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.8.jar:?]
	at com.sksamuel.exts.concurrent.ExecutorImplicits$RichExecutorService$$anon$2.run(ExecutorImplicits.scala:28) [exts_2.11-1.42.0.jar:1.42.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
```

**Comment by sksamuel** [comment]
Closing this because the implementation has changed in 1.2
