### ISSUE TITLE
Occur "Wrong FS: s3a" when using s3a with overwrite option.

### ISSUE THREAD

**Issue by StdCarrot** [51zero/eel-sdk#356]
When i try below
```scala
val source = new CsvSource(new Path("./some/local/path"))
val sink = new ParquetSink(new Path("s3a://some-bucket/path")).withOverwrite(true)
source.toDataStream().to(sink)
```

It occurred this
```java
[error] (run-main-0) java.lang.IllegalArgumentException: Wrong FS: s3a://some-bucket/path, expected: file:///
java.lang.IllegalArgumentException: Wrong FS: s3a://some-bucket/path, expected: file:///
        at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:645)
        at org.apache.hadoop.fs.RawLocalFileSystem.pathToFile(RawLocalFileSystem.java:80)
        at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:534)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:752)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:529)
        at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:409)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1400)
        at io.eels.component.parquet.ParquetSink$$anon$1.<init>(ParquetSink.scala:29)
        at io.eels.component.parquet.ParquetSink.io$eels$component$parquet$ParquetSink$$create(ParquetSink.scala:27)
        at io.eels.component.parquet.ParquetSink.open(ParquetSink.scala:52)
        at io.eels.datastream.SinkAction.execute(SinkAction.scala:46)
        at io.eels.datastream.DataStream$class.to(DataStream.scala:727)
        ....
```

But below works fine.
```scala
val source = new CsvSource(new Path("./some/local/path"))
val sink = new ParquetSink(new Path("s3a://some-bucket/path"))
source.toDataStream().to(sink)
```

Is it cause by hadoop?

**Comment by sksamuel** [comment]
The `fs:FileSystem` that is being passed implicitly is a local filesystem one. If you want to use s3, you need to create an s3 enabled filesystem object.

**Comment by StdCarrot** [comment]
Thank you for response.
But, I already set it like this.
```scala
  private implicit val conf = new Configuration()
  conf.set("fs.file.impl", classOf[org.apache.hadoop.fs.LocalFileSystem].getName)
  conf.set("fs.s3a.impl", classOf[org.apache.hadoop.fs.s3.S3FileSystem].getName)
  private implicit val fs: FileSystem = FileSystem.get(conf)
```

And when I remove option "overwrite", it works fine with S3.

**Comment by alexandruionita-gyg** [comment]
I ran into the same problem today and I realised that the FileSystem I was creating was a Local one instead of an S3 one. You can create an S3FileSystem by explicitly passing in an URI to your bucket. Also I would suggest using the S3AFileSystem instead since S3FileSystem seems to be deprecated.

```scala
private implicit val conf = new Configuration()
conf.set("fs.s3a.impl", classOf[org.apache.hadoop.fs.s3a.S3AFileSystem].getName)
private val uri = new URI("s3a://bucket_name")
private implicit val fs: FileSystem = FileSystem.get(uri, conf)
```

Hope this helps!

**Comment by garyfrost** [comment]
thanks @alexandruionita-gyg
